server:
  port: 8093

logging:
  level:
    com.mall.product.repository.ProductRepository: DEBUG

spring:
  application:
    name: product-service
  datasource:
    #url: jdbc:mysql://localhost:3306/product_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://127.0.0.1:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
